export const methodNames = {
  GET_PAIR: 'getPair',
  GET_RESERVES: 'getReserves',
  GET_AMOUNTS_OUT: 'getAmountsOut',
  GET_TOTAL_KAI_AMOUNTS_IN: 'getTotalKAIAmountsIn',
  ADD_LIQUIDITY: 'addLiquidity',
  ADD_LIQUIDITY_KAI: 'addLiquidityKAI',
  REMOVE_LIQUIDITY: 'removeLiquidity',
  REMOVE_LIQUIDITY_KAI: 'removeLiquidityKAI',
  SWAP_EXACT_TOKENS_FOR_TOKENS: 'swapExactTokensForTokens',
  SWAP_TOKENS_FOR_EXACT_TOKENS: 'swapTokensForExactTokens',
  SWAP_EXACT_KAI_FOR_TOKENS: 'swapExactKAIForTokens',
  SWAP_EXACT_TOKENS_FOR_KAI: 'swapExactTokensForKAI',
  SWAP_TOKENS_FOR_EXACT_KAI: 'swapTokensForExactKAI',
  SWAP_KAI_FOR_EXACT_TOKENS: 'swapKAIForExactTokens',

  APPROVE: 'approve',
  ALLOWANCE: 'allowance',
  BALANCE_OF: 'balanceOf',
  TOTAL_SUPPLY: 'totalSupply',
};
